# Whenever a PR is created, launch the tests 
# 

name: Execute test for PR
on:
  pull_request:
      types: [
        opened, 
        reopened,
        edited,
        synchronize
      ]
jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: Restore dotnet tools
        run: dotnet tool restore
      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          target: default